# Generated by Django 2.2 on 2020-06-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='resume_resume',
        ),
    ]
